---
# Adding plugins: https://pre-commit.com/#plugins

repos:

  # general linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.postman/collection.json'
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: pretty-format-json
        args: ['--no-sort-keys', '--autofix']
        exclude: '.postman/collection.json'
      - id: file-contents-sorter
        args: ['--ignore-case']
        files: '^(\.dockerignore|requirements\.txt|requirements-dev\.txt)$'

  # python linting
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black

  # python linting
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat

  # python linting
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.16.0
    hooks:
      - id: reorder-python-imports

  # python linting
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade

  # unicode character normalization
  - repo: https://github.com/sirosen/texthooks
    rev: 0.7.1
    hooks:
      - id: fix-smartquotes
      - id: fix-unicode-dashes

  # markdown linting
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0  # NOTE: v0.15.0 is giving a headache with pre-commit
    hooks:
      - id: markdownlint
        entry: mdl --style .markdownlint.rb
        exclude: ^node_modules/

  # CSS linting
  - repo: https://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
      - id: csslint
        files: ^application/static/css/.*\.css$

  # JavaScript linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.0.3
    hooks:
      - id: eslint
        files: \.js$
        types: [file]
        args: ['--max-warnings=0']

  # shell linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        entry: yamllint -c .yamllint.yaml .
